/* GENERATED by metal/gen_expert_bank_kernels.py from metal/moe.metal.
 * kernel_mul_mm_id source block sha256 0b5f89bedde551f33945359f30998a87e9ee0bf04ab1f3e90a8852f54de2af67.
 * Do not edit by hand: run the generator, or
 *   make check-expert-bank-kernels
 * to confirm this file is current. */
template<short NR1, typename S0, typename S0_4x4, typename S0_8x8, typename S1, typename S1_2x4, typename S1_8x8, typename block_q, short nl, void (*dequantize_func)(device const block_q *, short, thread S0_4x4 &), typename T0, typename T0_4x4, typename T1, typename T1_2x4, bool CULL_TAIL_SIMDGROUPS = false, short MB_ROWS = 0, bool A_DOUBLE_BUFFER = false>
kernel void kernel_glm53_expert_bank_mm_id(
        constant ds4_metal_args_mul_mm_id & args,
        device const char * src0,
        device const char * src1,
        device const char * htpe,
        device const char * hids,
        device       char * dst,
        device const char * work,
        threadgroup  char * shmem [[threadgroup(0)]],
        uint3  tgpig[[threadgroup_position_in_grid]],
        ushort tiitg[[thread_index_in_threadgroup]],
        ushort tiisg[[thread_index_in_simdgroup]],
        ushort sgitg[[simdgroup_index_in_threadgroup]]) {
    constexpr int NR0 = 64;
    static_assert(NR1 == 8 || NR1 == 16 || NR1 == 32,
                  "kernel_mul_mm_id accumulator layout supports 8, 16 or 32 routed rows");

    constexpr int NK  = 32;
    constexpr int NL0 = NK/16;
    constexpr int NL1 = NK/8;
    /* The A stage is NR0 rows x NK columns of S0 and does NOT depend on NR1.
     * (At NR1 = 32 this is the same 4096 bytes the fixed-width kernel used.) */
    constexpr int SA_BYTES = NR0 * NK * (int)sizeof(S0);

    /* Row-tile geometry. The routed tile is NR1 rows tall = NB blocks of 8;
     * the four simdgroups split the NR0 = 64 output rows SG_A ways and the
     * routed rows SG_B ways. At NR1 = 32 this reduces to the historical
     * 2 x 2 split (4 A blocks and 2 B blocks per simdgroup, mc[8]) and issues
     * the same MMA sequence per output element. Narrower tiles keep the same
     * per-element k order, so their results stay bit-identical. */
    constexpr int NB   = NR1/8;
    /* MB_ROWS overrides how many routed rows one simdgroup owns.  The point of
     * a smaller value at NR1 = 32 is CULL granularity: with 8 rows per
     * simdgroup an expert with 3 routed rows leaves three of the four
     * simdgroups with no MMA to issue at all, i.e. the MMA work of an 8-row
     * tile at the tile count of a 32-row one. */
    constexpr int MB_N = MB_ROWS ? MB_ROWS/8 : ((NR1 == 32) ? 2 : NB);
    constexpr int SG_B = NB/MB_N;                /* simdgroups over routed rows */
    constexpr int SG_A = 4/SG_B;                 /* simdgroups over output rows */
    constexpr int MA_N = 8/SG_A;                 /* A blocks per simdgroup */
    constexpr int MC_N = MA_N*MB_N;              /* accumulators per simdgroup */
    const short sg_a = (short)(sgitg % SG_A);
    const short sg_b = (short)(sgitg / SG_A);

    constexpr int SB_BYTES = NR1 * NK * (int)sizeof(S1);
    /* Single-buffered layout: [A][B].  Double-buffered: [A0][A1][B0][B1]. */
    threadgroup S0 * sa = (threadgroup S0 *)(shmem);
    threadgroup S1 * sb = (threadgroup S1 *)(shmem + (A_DOUBLE_BUFFER ? 2*SA_BYTES : SA_BYTES));
    /* Never dereferenced unless A_DOUBLE_BUFFER; folded away otherwise. */
    threadgroup S0 * sa1 = (threadgroup S0 *)(shmem + (A_DOUBLE_BUFFER ? SA_BYTES : 0));
    threadgroup S1 * sb1 = (threadgroup S1 *)(shmem + (A_DOUBLE_BUFFER ? 2*SA_BYTES + SB_BYTES : 0));

    device const uint32_t * work_count = (device const uint32_t *) work;
    const uint32_t work_index = tgpig.x;
    if (work_index >= work_count[0]) {
        return;
    }
    device const uint2 * work_items = (device const uint2 *)(work + 8);
    const uint2 item = work_items[work_index];
    const int im = (int)item.x;
    const int r0 = tgpig.y*NR0;
    const int r1 = (int)item.y;

    device const uint32_t * tpe_u32 = (device const uint32_t *) (htpe);
    device const int32_t  * ids_i32 = (device const int32_t  *) (hids);

    const int32_t neh1 = tpe_u32[im];

    if (r1 >= neh1) {
        return;
    }

    const short nr0 = (args.ne0 - r0 < NR0) ? (args.ne0 - r0) : NR0;
    const short nr1 = (    neh1 - r1 < NR1) ? (    neh1 - r1) : NR1;
    // Each simdgroup owns routed rows [8*MB_N*sg_b, +8*MB_N). Keep all
    // threads in staging and at every threadgroup barrier, but let a
    // simdgroup whose rows all lie past the end skip MMA on short final
    // expert tiles. (At NR1 = 32, SG_B = 2 and this is the historical
    // "second row-half" cull.)
    const bool mma_active =
        !CULL_TAIL_SIMDGROUPS || (short)(8*MB_N)*sg_b < nr1;

    if (!ds4_tp_owns_expert(im, args.ne02, args.tp_rank, args.tp_world)) {
        /* Unowned expert under the TP split: zero this tile's output rows so
         * the downstream swiglu/sum stages stay unchanged. Each (token,slot)
         * row belongs to exactly one expert, so nothing else writes them. */
        for (short j = sgitg; j < nr1; j += 4) {
            const int idj = ids_i32[im*args.ne21 + r1 + j];

            const short ide = idj % args.ne20;
            const int   idt = idj / args.ne20;

            device float * D = (device float *) dst + r0 + ide*args.ne0 + idt*args.ne1*args.ne0;

            for (int i = tiisg; i < nr0; i += 32) {
                D[i] = 0.0f;
            }
        }
        return;
    }

    const short lr0 = ((short)tiitg/NL0) < nr0 ? ((short)tiitg/NL0) : nr0 - 1;
    const short lr1 = ((short)tiitg/NL1) < nr1 ? ((short)tiitg/NL1) : nr1 - 1;

    const short il0 = (tiitg % NL0);


    const int id = ids_i32[im*args.ne21 + r1 + lr1];

    const short i11 = (id % args.ne20) % args.ne11;
    const int   i12 = (id / args.ne20);
    const short i13 = 0;

    const uint64_t offset0 = (uint64_t)(im - args.tp_expert_base)*args.nb02 + i13*args.nb03;

    /* Bank layout: expert base, then (r0/NR0) output blocks of
     * (ne00/NK) tiles of SA_BYTES, then one tile per k-step. */
    device const uint4 * tsrc = (device const uint4 *)(src0 + offset0
        + (uint64_t)(r0/NR0)*((uint64_t)args.ne00/NK)*SA_BYTES);

    const short iy = 8*(tiitg % NL1);

    device const T1 * y = (device const T1 *)(src1
        + args.nb13*i13
        + args.nb12*i12
        + args.nb11*i11
        + args.nb10*iy);

    S0_8x8 ma[MA_N];
    S1_8x8 mb[MB_N];

    simdgroup_float8x8 mc[MC_N];

    for (short i = 0; i < MC_N; i++){
        mc[i] = make_filled_simdgroup_matrix<float, 8>(0.f);
    }

    for (int loop_k = 0; loop_k < args.ne00; loop_k += NK) {
        /* The 4 KiB tile is already in `sa` order.  Issue the device
         * loads BEFORE the barrier -- exactly where the shipped path
         * issues dequantize_func -- then store them cooperatively.
         * 128 threads x two 16 B loads covers SA_BYTES. */
        const uint4 tv0 = tsrc[tiitg];
        const uint4 tv1 = tsrc[tiitg + SA_BYTES/32];

        threadgroup_barrier(mem_flags::mem_threadgroup);

        ((threadgroup uint4 *) sa)[tiitg]                = tv0;
        ((threadgroup uint4 *) sa)[tiitg + SA_BYTES/32] = tv1;

        /* Threads whose routed row lies outside the (narrow) tile stage
         * nothing; at NR1 = 32 every thread of the 128-thread threadgroup
         * owns a row and the guard folds away at compile time. */
        if (NR1 == 32 || (short)(tiitg/NL1) < NR1) {
            if (FC_mul_mm_bc_inp) {
                for (short i = 0; i < 8; ++i) {
                    const short sx = (tiitg%NL1);
                    const short sy = (tiitg/NL1)/8;

                    const short lx = i;
                    const short ly = (tiitg/NL1)%8;

                    const short ib = NB*sx + sy;

                    *(sb + 64*ib + 8*ly + lx) = loop_k + iy + i < args.ne00 ? (S1) *((device T1 *) y + i) : 0;
                }
            } else {
                const short sx = (tiitg%NL1);
                const short sy = (tiitg/NL1)/8;

                const short ly = (tiitg/NL1)%8;

                const short ib = NB*sx + sy;

                *(threadgroup S1_2x4 *)(sb + 64*ib + 8*ly) = (S1_2x4)(*((device T1_2x4 *) y));
            }
        }

        y += NK;

        threadgroup_barrier(mem_flags::mem_threadgroup);

        threadgroup const S0 * lsma = (sa + MA_N*64*sg_a);
        threadgroup const S1 * lsmb = (sb + MB_N*64*sg_b);

        if (mma_active) {
            FOR_UNROLL (short ik = 0; ik < NK/8; ik++) {
                simdgroup_barrier(mem_flags::mem_none);

                FOR_UNROLL (short i = 0; i < MA_N; i++) {
                    simdgroup_load(ma[i], lsma + 64*i, 8, 0, false);
                }

                simdgroup_barrier(mem_flags::mem_none);

                FOR_UNROLL (short i = 0; i < MB_N; i++) {
                    simdgroup_load(mb[i], lsmb + 64*i, 8, 0, false);
                }

                simdgroup_barrier(mem_flags::mem_none);

                FOR_UNROLL (short i = 0; i < MC_N; i++){
                    simdgroup_multiply_accumulate(mc[i], mb[i/MA_N], ma[i%MA_N], mc[i]);
                }

                lsma += 8*64;
                lsmb += NB*64;
            }
        }
        tsrc += SA_BYTES/16;
    }

    threadgroup_barrier(mem_flags::mem_threadgroup);

    threadgroup float * temp_str = ((threadgroup float *) shmem)
        + (8*MA_N)*sg_a + ((8*MB_N)*sg_b)*NR0;

    if (mma_active) {
        for (short i = 0; i < MC_N; i++) {
            simdgroup_store(mc[i], temp_str + 8*(i%MA_N) + 8*NR0*(i/MA_N), NR0, 0, false);
        }
    }

    threadgroup_barrier(mem_flags::mem_threadgroup);

    for (short j = sgitg; j < nr1; j += 4) {
        const int idj = ids_i32[im*args.ne21 + r1 + j];

        const short ide = idj % args.ne20;
        const int   idt = idj / args.ne20;

        device float  * D  = (device float  *) dst + r0 + ide*args.ne0 + idt*args.ne1*args.ne0;
        device float4 * D4 = (device float4 *) D;

        threadgroup float  * C  = (threadgroup float  *) shmem + j*NR0;
        threadgroup float4 * C4 = (threadgroup float4 *) C;

        int i = tiisg;
        for (; i < nr0/4; i += 32) {
            *(D4 + i) = *(C4 + i);
        }

        i = (4*(nr0/4)) + tiisg;
        for (; i < nr0; i += 32) {
            *(D + i) = *(C + i);
        }
    }
}


typedef decltype(kernel_glm53_expert_bank_mm_id<32, half, half4x4, simdgroup_half8x8, half, half2x4, simdgroup_half8x8, half4x4, 1, dequantize_f16, half, half4x4, float, float2x4, true, 8>) kernel_glm53_expert_bank_mm_id_f32_t;
template [[host_name("kernel_glm53_expert_bank_mm_id_f32_cull4")]] kernel kernel_glm53_expert_bank_mm_id_f32_t kernel_glm53_expert_bank_mm_id<32, half, half4x4, simdgroup_half8x8, half, half2x4, simdgroup_half8x8, half4x4, 1, dequantize_f16, half, half4x4, float, float2x4, true, 8>;

typedef decltype(kernel_glm53_expert_bank_mm_id<32, half, half4x4, simdgroup_half8x8, half, half2x4, simdgroup_half8x8, half4x4, 1, dequantize_f16, half, half4x4, half, half2x4, true, 8>) kernel_glm53_expert_bank_mm_id_f16_t;
template [[host_name("kernel_glm53_expert_bank_mm_id_f16_cull4")]] kernel kernel_glm53_expert_bank_mm_id_f16_t kernel_glm53_expert_bank_mm_id<32, half, half4x4, simdgroup_half8x8, half, half2x4, simdgroup_half8x8, half4x4, 1, dequantize_f16, half, half4x4, half, half2x4, true, 8>;

#define DS4_GLM53_WIDE_DS4_MMID_STAGE_A(DST_, K_) do {                                        \
    if (is_same<T0_4x4, block_q>::value && FC_mul_mm_bc_inp) {                 \
        for (short i = 0; i < 16; i++) {                                       \
            const short sx = 2*il0 + i/8;                                      \
            const short sy = (tiitg/NL0)/8;                                    \
            const short lx = (tiitg/NL0)%8;                                    \
            const short ly = i%8;                                              \
            const short ib = 8*sx + sy;                                        \
            *((DST_) + 64*ib + 8*ly + lx) =                                    \
                (K_) + 16*il + i < args.ne00 ? *((device T0 *) x + i) : 0;     \
        }                                                                      \
    } else {                                                                   \
        S0_4x4 temp_a;                                                         \
        dequantize_func(x, il, temp_a);                                        \
        FOR_UNROLL (short i = 0; i < 16; i++) {                                \
            const short sx = 2*il0 + i/8;                                      \
            const short sy = (tiitg/NL0)/8;                                    \
            const short lx = (tiitg/NL0)%8;                                    \
            const short ly = i%8;                                              \
            const short ib = 8*sx + sy;                                        \
            *((DST_) + 64*ib + 8*ly + lx) = temp_a[i/4][i%4];                  \
        }                                                                      \
    }                                                                          \
} while (0)

#define DS4_GLM53_WIDE_DS4_MMID_STAGE_B(DST_, K_) do {                                        \
    if (NR1 == 32 || (short)(tiitg/NL1) < NR1) {                               \
        if (FC_mul_mm_bc_inp) {                                                \
            for (short i = 0; i < 8; ++i) {                                    \
                const short sx = (tiitg%NL1);                                  \
                const short sy = (tiitg/NL1)/8;                                \
                const short lx = i;                                            \
                const short ly = (tiitg/NL1)%8;                                \
                const short ib = NB*sx + sy;                                   \
                *((DST_) + 64*ib + 8*ly + lx) =                                \
                    (K_) + iy + i < args.ne00 ? (S1) *((device T1 *) y + i) : 0;\
            }                                                                  \
        } else {                                                               \
            const short sx = (tiitg%NL1);                                      \
            const short sy = (tiitg/NL1)/8;                                    \
            const short ly = (tiitg/NL1)%8;                                    \
            const short ib = NB*sx + sy;                                       \
            *(threadgroup S1_2x4 *)((DST_) + 64*ib + 8*ly) =                   \
                (S1_2x4)(*((device T1_2x4 *) y));                              \
        }                                                                      \
    }                                                                          \
} while (0)

#define DS4_GLM53_WIDE_DS4_MMID_ADVANCE() do {                                                \
    il = (il + 2 < nl) ? il + 2 : il % 2;                                      \
    x  = (il < 2) ? x + (2 + nl - 1)/nl : x;                                   \
    y += NK;                                                                   \
} while (0)

template<short NR1, typename S0, typename S0_4x4, typename S0_8x8, typename S1, typename S1_2x4, typename S1_8x8, typename block_q, short nl, void (*dequantize_func)(device const block_q *, short, thread S0_4x4 &), typename T0, typename T0_4x4, typename T1, typename T1_2x4, bool CULL_TAIL_SIMDGROUPS = false, short MB_ROWS = 0, bool A_DOUBLE_BUFFER = false>
kernel void kernel_glm53_wide_mul_mm_id(
        constant ds4_metal_args_mul_mm_id & args,
        device const char * src0,
        device const char * src1,
        device const char * htpe,
        device const char * hids,
        device       char * dst,
        device const char * work,
        threadgroup  char * shmem [[threadgroup(0)]],
        uint3  tgpig[[threadgroup_position_in_grid]],
        ushort tiitg[[thread_index_in_threadgroup]],
        ushort tiisg[[thread_index_in_simdgroup]],
        ushort sgitg[[simdgroup_index_in_threadgroup]]) {
    constexpr int NR0 = 64;
    static_assert(NR1 == 8 || NR1 == 16 || NR1 == 32,
                  "kernel_mul_mm_id accumulator layout supports 8, 16 or 32 routed rows");

    constexpr int NK  = 32;
    constexpr int NL0 = NK/16;
    constexpr int NL1 = NK/8;
    /* The A stage is NR0 rows x NK columns of S0 and does NOT depend on NR1.
     * (At NR1 = 32 this is the same 4096 bytes the fixed-width kernel used.) */
    constexpr int SA_BYTES = NR0 * NK * (int)sizeof(S0);

    /* Row-tile geometry. The routed tile is NR1 rows tall = NB blocks of 8;
     * the four simdgroups split the NR0 = 64 output rows SG_A ways and the
     * routed rows SG_B ways. At NR1 = 32 this reduces to the historical
     * 2 x 2 split (4 A blocks and 2 B blocks per simdgroup, mc[8]) and issues
     * the same MMA sequence per output element. Narrower tiles keep the same
     * per-element k order, so their results stay bit-identical. */
    constexpr int NB   = NR1/8;
    /* MB_ROWS overrides how many routed rows one simdgroup owns.  The point of
     * a smaller value at NR1 = 32 is CULL granularity: with 8 rows per
     * simdgroup an expert with 3 routed rows leaves three of the four
     * simdgroups with no MMA to issue at all, i.e. the MMA work of an 8-row
     * tile at the tile count of a 32-row one. */
    constexpr int MB_N = MB_ROWS ? MB_ROWS/8 : ((NR1 == 32) ? 2 : NB);
    constexpr int SG_B = NB/MB_N;                /* simdgroups over routed rows */
    constexpr int SG_A = 4/SG_B;                 /* simdgroups over output rows */
    constexpr int MA_N = 8/SG_A;                 /* A blocks per simdgroup */
    constexpr int MC_N = MA_N*MB_N;              /* accumulators per simdgroup */
    const short sg_a = (short)(sgitg % SG_A);
    const short sg_b = (short)(sgitg / SG_A);

    constexpr int SB_BYTES = NR1 * NK * (int)sizeof(S1);
    /* Single-buffered layout: [A][B].  Double-buffered: [A0][A1][B0][B1]. */
    threadgroup S0 * sa = (threadgroup S0 *)(shmem);
    threadgroup S1 * sb = (threadgroup S1 *)(shmem + (A_DOUBLE_BUFFER ? 2*SA_BYTES : SA_BYTES));
    /* Never dereferenced unless A_DOUBLE_BUFFER; folded away otherwise. */
    threadgroup S0 * sa1 = (threadgroup S0 *)(shmem + (A_DOUBLE_BUFFER ? SA_BYTES : 0));
    threadgroup S1 * sb1 = (threadgroup S1 *)(shmem + (A_DOUBLE_BUFFER ? 2*SA_BYTES + SB_BYTES : 0));

    device const uint32_t * work_count = (device const uint32_t *) work;
    const uint32_t work_index = tgpig.x;
    if (work_index >= work_count[0]) {
        return;
    }
    device const uint2 * work_items = (device const uint2 *)(work + 8);
    const uint2 item = work_items[work_index];
    const int im = (int)item.x;
    const int r0 = tgpig.y*NR0;
    const int r1 = (int)item.y;

    device const uint32_t * tpe_u32 = (device const uint32_t *) (htpe);
    device const int32_t  * ids_i32 = (device const int32_t  *) (hids);

    const int32_t neh1 = tpe_u32[im];

    if (r1 >= neh1) {
        return;
    }

    const short nr0 = (args.ne0 - r0 < NR0) ? (args.ne0 - r0) : NR0;
    const short nr1 = (    neh1 - r1 < NR1) ? (    neh1 - r1) : NR1;
    // Each simdgroup owns routed rows [8*MB_N*sg_b, +8*MB_N). Keep all
    // threads in staging and at every threadgroup barrier, but let a
    // simdgroup whose rows all lie past the end skip MMA on short final
    // expert tiles. (At NR1 = 32, SG_B = 2 and this is the historical
    // "second row-half" cull.)
    const bool mma_active =
        !CULL_TAIL_SIMDGROUPS || (short)(8*MB_N)*sg_b < nr1;

    if (!ds4_tp_owns_expert(im, args.ne02, args.tp_rank, args.tp_world)) {
        /* Unowned expert under the TP split: zero this tile's output rows so
         * the downstream swiglu/sum stages stay unchanged. Each (token,slot)
         * row belongs to exactly one expert, so nothing else writes them. */
        for (short j = sgitg; j < nr1; j += 4) {
            const int idj = ids_i32[im*args.ne21 + r1 + j];

            const short ide = idj % args.ne20;
            const int   idt = idj / args.ne20;

            device float * D = (device float *) dst + r0 + ide*args.ne0 + idt*args.ne1*args.ne0;

            for (int i = tiisg; i < nr0; i += 32) {
                D[i] = 0.0f;
            }
        }
        return;
    }

    const short lr0 = ((short)tiitg/NL0) < nr0 ? ((short)tiitg/NL0) : nr0 - 1;
    const short lr1 = ((short)tiitg/NL1) < nr1 ? ((short)tiitg/NL1) : nr1 - 1;

    const short il0 = (tiitg % NL0);

    short il = il0;

    const int id = ids_i32[im*args.ne21 + r1 + lr1];

    const short i11 = (id % args.ne20) % args.ne11;
    const int   i12 = (id / args.ne20);
    const short i13 = 0;

    const uint64_t offset0 = (uint64_t)(im - args.tp_expert_base)*args.nb02 + i13*args.nb03;
    const short    offset1 = il0/nl;

    device const block_q * x = (device const block_q *)(src0 + args.nb01*(r0 + lr0) + offset0) + offset1;

    const short iy = 8*(tiitg % NL1);

    device const T1 * y = (device const T1 *)(src1
        + args.nb13*i13
        + args.nb12*i12
        + args.nb11*i11
        + args.nb10*iy);

    S0_8x8 ma[MA_N];
    S1_8x8 mb[MB_N];

    simdgroup_float8x8 mc[MC_N];

    for (short i = 0; i < MC_N; i++){
        mc[i] = make_filled_simdgroup_matrix<float, 8>(0.f);
    }

    if (A_DOUBLE_BUFFER) {
        /* Stage k = 0, then in every iteration stage k+1 into the spare half
         * while the MMA consumes the current half.  One barrier per k-step. */
        int stage_k = 0;
        DS4_GLM53_WIDE_DS4_MMID_STAGE_A(sa, stage_k);
        DS4_GLM53_WIDE_DS4_MMID_STAGE_B(sb, stage_k);
        DS4_GLM53_WIDE_DS4_MMID_ADVANCE();
        stage_k += NK;

        threadgroup_barrier(mem_flags::mem_threadgroup);

        bool ph = false;
        for (int loop_k = 0; loop_k < args.ne00; loop_k += NK) {
            threadgroup S0 * nxt_a = ph ? sa  : sa1;
            threadgroup S1 * nxt_b = ph ? sb  : sb1;
            threadgroup const S0 * cur_a = ph ? sa1 : sa;
            threadgroup const S1 * cur_b = ph ? sb1 : sb;

            if (stage_k < args.ne00) {
                DS4_GLM53_WIDE_DS4_MMID_STAGE_A(nxt_a, stage_k);
                DS4_GLM53_WIDE_DS4_MMID_STAGE_B(nxt_b, stage_k);
                DS4_GLM53_WIDE_DS4_MMID_ADVANCE();
                stage_k += NK;
            }

            threadgroup const S0 * lsma = (cur_a + MA_N*64*sg_a);
            threadgroup const S1 * lsmb = (cur_b + MB_N*64*sg_b);

            if (mma_active) {
                FOR_UNROLL (short ik = 0; ik < NK/8; ik++) {
                    simdgroup_barrier(mem_flags::mem_none);

                    FOR_UNROLL (short i = 0; i < MA_N; i++) {
                        simdgroup_load(ma[i], lsma + 64*i, 8, 0, false);
                    }

                    simdgroup_barrier(mem_flags::mem_none);

                    FOR_UNROLL (short i = 0; i < MB_N; i++) {
                        simdgroup_load(mb[i], lsmb + 64*i, 8, 0, false);
                    }

                    simdgroup_barrier(mem_flags::mem_none);

                    FOR_UNROLL (short i = 0; i < MC_N; i++){
                        simdgroup_multiply_accumulate(mc[i], mb[i/MA_N], ma[i%MA_N], mc[i]);
                    }

                    lsma += 8*64;
                    lsmb += NB*64;
                }
            }

            threadgroup_barrier(mem_flags::mem_threadgroup);
            ph = !ph;
        }
    } else {
    for (int loop_k = 0; loop_k < args.ne00; loop_k += NK) {
        if (is_same<T0_4x4, block_q>::value && FC_mul_mm_bc_inp) {
            threadgroup_barrier(mem_flags::mem_threadgroup);

            for (short i = 0; i < 16; i++) {
                const short sx = 2*il0 + i/8;
                const short sy = (tiitg/NL0)/8;

                const short lx = (tiitg/NL0)%8;
                const short ly = i%8;

                const short ib = 8*sx + sy;

                *(sa + 64*ib + 8*ly + lx) = loop_k + 16*il + i < args.ne00 ? *((device T0 *) x + i) : 0;
            }
        } else {
            S0_4x4 temp_a;
            dequantize_func(x, il, temp_a);

            threadgroup_barrier(mem_flags::mem_threadgroup);

            FOR_UNROLL (short i = 0; i < 16; i++) {
                const short sx = 2*il0 + i/8;
                const short sy = (tiitg/NL0)/8;

                const short lx = (tiitg/NL0)%8;
                const short ly = i%8;

                const short ib = 8*sx + sy;

                *(sa + 64*ib + 8*ly + lx) = temp_a[i/4][i%4];
            }
        }

        /* Threads whose routed row lies outside the (narrow) tile stage
         * nothing; at NR1 = 32 every thread of the 128-thread threadgroup
         * owns a row and the guard folds away at compile time. */
        if (NR1 == 32 || (short)(tiitg/NL1) < NR1) {
            if (FC_mul_mm_bc_inp) {
                for (short i = 0; i < 8; ++i) {
                    const short sx = (tiitg%NL1);
                    const short sy = (tiitg/NL1)/8;

                    const short lx = i;
                    const short ly = (tiitg/NL1)%8;

                    const short ib = NB*sx + sy;

                    *(sb + 64*ib + 8*ly + lx) = loop_k + iy + i < args.ne00 ? (S1) *((device T1 *) y + i) : 0;
                }
            } else {
                const short sx = (tiitg%NL1);
                const short sy = (tiitg/NL1)/8;

                const short ly = (tiitg/NL1)%8;

                const short ib = NB*sx + sy;

                *(threadgroup S1_2x4 *)(sb + 64*ib + 8*ly) = (S1_2x4)(*((device T1_2x4 *) y));
            }
        }

        il = (il + 2 < nl) ? il + 2 : il % 2;
        x  = (il < 2) ? x + (2 + nl - 1)/nl : x;

        y += NK;

        threadgroup_barrier(mem_flags::mem_threadgroup);

        threadgroup const S0 * lsma = (sa + MA_N*64*sg_a);
        threadgroup const S1 * lsmb = (sb + MB_N*64*sg_b);

        if (mma_active) {
            FOR_UNROLL (short ik = 0; ik < NK/8; ik++) {
                simdgroup_barrier(mem_flags::mem_none);

                FOR_UNROLL (short i = 0; i < MA_N; i++) {
                    simdgroup_load(ma[i], lsma + 64*i, 8, 0, false);
                }

                simdgroup_barrier(mem_flags::mem_none);

                FOR_UNROLL (short i = 0; i < MB_N; i++) {
                    simdgroup_load(mb[i], lsmb + 64*i, 8, 0, false);
                }

                simdgroup_barrier(mem_flags::mem_none);

                FOR_UNROLL (short i = 0; i < MC_N; i++){
                    simdgroup_multiply_accumulate(mc[i], mb[i/MA_N], ma[i%MA_N], mc[i]);
                }

                lsma += 8*64;
                lsmb += NB*64;
            }
        }
    }
    }

    threadgroup_barrier(mem_flags::mem_threadgroup);

    threadgroup float * temp_str = ((threadgroup float *) shmem)
        + (8*MA_N)*sg_a + ((8*MB_N)*sg_b)*NR0;

    if (mma_active) {
        for (short i = 0; i < MC_N; i++) {
            simdgroup_store(mc[i], temp_str + 8*(i%MA_N) + 8*NR0*(i/MA_N), NR0, 0, false);
        }
    }

    threadgroup_barrier(mem_flags::mem_threadgroup);

    for (short j = sgitg; j < nr1; j += 4) {
        const int idj = ids_i32[im*args.ne21 + r1 + j];

        const short ide = idj % args.ne20;
        const int   idt = idj / args.ne20;

        device float  * D  = (device float  *) dst + r0 + ide*args.ne0 + idt*args.ne1*args.ne0;
        device float4 * D4 = (device float4 *) D;

        threadgroup float  * C  = (threadgroup float  *) shmem + j*NR0;
        threadgroup float4 * C4 = (threadgroup float4 *) C;

        int i = tiisg;
        for (; i < nr0/4; i += 32) {
            *(D4 + i) = *(C4 + i);
        }

        i = (4*(nr0/4)) + tiisg;
        for (; i < nr0; i += 32) {
            *(D + i) = *(C + i);
        }
    }
}

#undef DS4_GLM53_WIDE_DS4_MMID_STAGE_A
#undef DS4_GLM53_WIDE_DS4_MMID_STAGE_B
#undef DS4_GLM53_WIDE_DS4_MMID_ADVANCE
typedef decltype(kernel_glm53_wide_mul_mm_id<32, half, half4x4, simdgroup_half8x8, half, half2x4, simdgroup_half8x8, block_q4_K, 16, dequantize_q4_K_w16, float, float4x4, float, float2x4, true, 8>) glm53_wide_q4_f32_t;
template [[host_name("kernel_glm53_wide_mul_mm_id_q4_K_f32_cull4_w16")]] kernel glm53_wide_q4_f32_t kernel_glm53_wide_mul_mm_id<32, half, half4x4, simdgroup_half8x8, half, half2x4, simdgroup_half8x8, block_q4_K, 16, dequantize_q4_K_w16, float, float4x4, float, float2x4, true, 8>;

typedef decltype(kernel_glm53_wide_mul_mm_id<32, half, half4x4, simdgroup_half8x8, half, half2x4, simdgroup_half8x8, block_q4_K, 16, dequantize_q4_K_w16, half, half4x4, half, half2x4, true, 8>) glm53_wide_q4_f16_t;
template [[host_name("kernel_glm53_wide_mul_mm_id_q4_K_f16_cull4_w16")]] kernel glm53_wide_q4_f16_t kernel_glm53_wide_mul_mm_id<32, half, half4x4, simdgroup_half8x8, half, half2x4, simdgroup_half8x8, block_q4_K, 16, dequantize_q4_K_w16, half, half4x4, half, half2x4, true, 8>;


/* ---------------- expert-bank expansion and verification ----------------
 *
 * bank[e][o/64][k/32][(k%32)/8][(o%64)/8][k%8][o%8] = dequantize_q4_K(...)
 * for output row o, reduction element k of expert e: each 64-output x
 * 32-reduction block is 4096 contiguous bytes in exactly the order
 * kernel_mul_mm_id's `sa` stage holds them.  The writer below builds one such
 * block per threadgroup using the SHIPPED staging expression itself, and the
 * halves it stores are by construction the values dequantize_q4_K produces for
 * the packed kernel's A stage -- same file, same decoded values, no
 * requantization and no precision change.
 *
 * From ~/src/ds4-wt-audit-tilemajor (cbb6bc3) audit-tilemajor-harness/tm.metal
 * kernel_tm_q4k_to_T / kernel_tm_verify_T, renamed only. */
typedef struct {
    uint  rows;        /* output rows per expert (ne0)      */
    uint  ne00;        /* reduction length (k)              */
    ulong row_bytes;   /* packed Q4_K row stride            */
    uint  kblocks;     /* ne00/32                           */
    uint  n_expert;    /* 288                               */
} glm53_expert_bank_args;

/* 128 threads per (expert, 64-row output block, 32-wide reduction block).
 * Thread t dequantizes the sixteen halves of output row t/2 at k-offsets
 * 16*(t%2) .. +16 -- the same sixteen a thread of the GEMM stages -- writes
 * them through the shipped A-stage expression into a 4 KiB threadgroup tile,
 * then the tile is stored as one contiguous bank block. */
kernel void kernel_glm53_expert_bank_expand(
        device const char  * src,
        device       half  * dst,
        constant glm53_expert_bank_args & a,
        threadgroup  half  * tile [[threadgroup(0)]],
        uint3  tgpig [[threadgroup_position_in_grid]],
        ushort tiitg [[thread_index_in_threadgroup]]) {
    const uint   kb      = tgpig.x;
    const uint   ob      = tgpig.y;
    const uint   e       = tgpig.z;
    const ushort o_local = tiitg >> 1;
    const ushort h       = tiitg & 1;
    const ulong  row     = (ulong)e*a.rows + (ulong)ob*64ul + o_local;
    const uint   k0      = kb*32u + h*16u;
    device const block_q4_K * xb =
        (device const block_q4_K *)(src + row*a.row_bytes) + (k0 >> 8);
    half4x4 t;
    dequantize_q4_K(xb, (short)((k0 >> 4) & 15u), t);
    FOR_UNROLL (short i = 0; i < 16; i++) {
        const short sx = 2*(short)h + i/8;
        const short sy = (short)(o_local/8);
        const short lx = (short)(o_local%8);
        const short ly = i%8;
        const short ib = 8*sx + sy;
        tile[64*ib + 8*ly + lx] = t[i/4][i%4];
    }
    threadgroup_barrier(mem_flags::mem_threadgroup);
    device uint4 * o = (device uint4 *)(dst +
        ((((ulong)e*(a.rows/64ul) + ob)*a.kblocks + kb) << 11));
    threadgroup const uint4 * s = (threadgroup const uint4 *)tile;
    o[tiitg]       = s[tiitg];
    o[tiitg + 128] = s[tiitg + 128];
}

/* Re-dequantize the packed weights and compare every half against the bank
 * through the INVERSE index mapping, independently of the writer above.
 * ctr[0] mismatching halves, ctr[1] halves compared, ctr[2] one mismatching
 * flat index, ctr[3] halves that are finite. */
kernel void kernel_glm53_expert_bank_verify(
        device const char  * src,
        device const half  * dst,
        device atomic_uint * ctr,
        constant glm53_expert_bank_args & a,
        uint   gid   [[thread_position_in_grid]],
        ushort tiisg [[thread_index_in_simdgroup]]) {
    uint mism = 0, cmpd = 0, fin = 0;
    const ulong groups = a.ne00/16u;
    const ulong g   = (ulong)gid;
    const ulong row = g / groups;
    if (row < (ulong)a.n_expert*a.rows) {
        const ulong gr = g - row*groups;
        const ulong e  = row / a.rows;
        const ulong o  = row - e*a.rows;
        const uint  k0 = (uint)(gr*16ul);
        device const block_q4_K * xb =
            (device const block_q4_K *)(src + row*a.row_bytes) + (k0 >> 8);
        half4x4 t;
        dequantize_q4_K(xb, (short)((k0 >> 4) & 15u), t);
        for (short i = 0; i < 16; i++) {
            const uint  k = k0 + (uint)i;
            const ulong idx = ((((e*(a.rows/64ul) + (o >> 6))*a.kblocks + (k >> 5)) << 11)
                               + 512ul*((k & 31u) >> 3)
                               +  64ul*((o & 63ul) >> 3)
                               +   8ul*(k & 7u)
                               +       (o & 7ul));
            const half want = t[i/4][i%4];
            const half got  = dst[idx];
            if (as_type<ushort>(want) != as_type<ushort>(got)) {
                mism++;
                atomic_store_explicit(ctr + 2, (uint)idx, memory_order_relaxed);
            }
            cmpd++;
            if (isfinite((float)want)) fin++;
        }
    }
    mism = simd_sum(mism); cmpd = simd_sum(cmpd); fin = simd_sum(fin);
    if (tiisg == 0) {
        if (mism) atomic_fetch_add_explicit(ctr + 0, mism, memory_order_relaxed);
        if (cmpd) atomic_fetch_add_explicit(ctr + 1, cmpd, memory_order_relaxed);
        if (fin)  atomic_fetch_add_explicit(ctr + 3, fin,  memory_order_relaxed);
    }
}
